import './globals.css'
import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Header } from '@/app/components/Header'
import ThemeRegistry from '@/app/components/ThemeRegistry'
import { inter, roboto_mono } from '@/app/fonts'
import { Footer } from '@/app/components/Footer'
import { QuoterBanner } from '@/app/components/QuoterBanner'
import { HeroBanner } from '@/app/components/HeroBanner'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="es">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;800&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={`${inter.className} ${roboto_mono.className}`}>
        <ThemeRegistry options={{ key: 'mui' }}>
          <Header />
          <HeroBanner />
          {children}
          <QuoterBanner />
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  )
}
